// @flow strict
import type {downtimeRecord} from "./types";

/* eslint-disable object-property-newline */
export const data: Array<downtimeRecord> = [
  {
    id: "0",
    date: new Date("20-Feb-19"),
    machinery: "Crusher",
    group: "Mechanical",
    advent: "Planned",
    equipment: "121-CR-001",
    downtimeInfo: "Construction Downtime",
    timeOffOn: "05:00/09:25",
    minutesOff: 265,
  },
  {
    id: "1",
    machinery: "Crusher",
    date: new Date("20-Feb-19"),
    group: "Electrical",
    advent: "Unplanned",
    equipment: "121-FE-001",
    downtimeInfo: "Apron feeder tripped",
    timeOffOn: "09:23/09:32",
    minutesOff: 10,
  },
  {
    id: "2",
    date: new Date("20-Feb-19"),
    machinery: "Crusher",
    group: "Operational",
    advent: "Unplanned",
    equipment: "121-CV-001",
    downtimeInfo: "CV-01 pullwire activated",
    timeOffOn: "10:28/10:31",
    minutesOff: 3,
  },
  {
    id: "3",
    date: new Date("21-Feb-19"),
    machinery: "Crusher",
    group: "Mechanical",
    advent: "Planned",
    equipment: "121-CR-001",
    downtimeInfo: "Construction Downtime",
    timeOffOn: "05:00/07:34",
    minutesOff: 154,
  },
  {
    id: "4",
    date: new Date("22-Feb-19"),
    machinery: "Crusher",
    group: "Operational",
    advent: "Unplanned",
    equipment: "121-CR-001",
    downtimeInfo: "Stand by due to Milling shutdown",
    timeOffOn: "05:00/07:19",
    minutesOff: 139,
  },
  {
    id: "5",
    date: new Date("20-Feb-19"),
    machinery: "Mill",
    group: "Mechanical",
    advent: "Planned",
    equipment: "131-BN-001",
    downtimeInfo: "Commissioning",
    timeOffOn: "05:00/05:00",
    minutesOff: 1440,
  },
  {
    id: "6",
    machinery: "Mill",
    date: new Date("21-Feb-19"),
    group: "Mechanical",
    advent: "Planned",
    equipment: "132-ML-001",
    downtimeInfo: "Commissioning",
    timeOffOn: "05:00/08:30",
    minutesOff: 210,
  },
  {
    id: "7",
    date: new Date("21-Feb-19"),
    machinery: "Mill",
    group: "Mechanical",
    advent: "Unplanned",
    equipment: "131-FE-001",
    downtimeInfo: "Surge bin Feeder VSD problem",
    timeOffOn: "09:57/15:15",
    minutesOff: 318,
  },
  {
    id: "8",
    date: new Date("22-Feb-19"),
    machinery: "Mill",
    group: "Mechanical",
    advent: "Unplanned",
    equipment: "132-ML-001",
    downtimeInfo: "Mill Retorque",
    timeOffOn: "05:00/07:34",
    minutesOff: 154,
  },
  {
    id: "9",
    date: new Date("26-Feb-19"),
    machinery: "Mill",
    group: "Mechanical",
    advent: "Planned",
    equipment: "132-ML-001",
    downtimeInfo: "Construction Downtime",
    timeOffOn: "17:00/05:00",
    minutesOff: 720,
  },
];
